
# Simulation
```{r setup, include=FALSE}
# Packages
library(tidyverse)
library(modelr)
options(na.action = na.warn)
```

## Build a test set of sample users
```{r}
# Create test set, each column representing a question in the "should you get a dog?" function
Input.df <-  data.frame(AgeInput=integer(),HomeInput=integer(),MentalHealthInput=integer(),PhysicalHealthInput=integer(),LivingWithInput=integer(),AllergiesInput=integer(),PriorOwnershipInput=integer(),ExpensesInput=integer(), Score=double())
# sample size (num of users to simulate)
N <- 100 

# For each user (row) in test set, generate inputs to each question (column)
for (i in 1:N) {
  
  # Generate random inputs 
  AgeInput <- sample(0:100, 1) #number = age
  HomeInput <- sample(0:1, 1) #0 = house, 1=apartment
  MentalHealthInput <- sample(0:1, 1) #0 = yes, 1=no
  PhysicalHealthInput <- sample(0:1, 1) #0 = yes, 1=no
  LivingWithInput <- sample(0:1, 1) #0 = alone, 1=withOthers
  AllergiesInput <- sample(0:1, 1) #0 = yes, 1=no
  PriorOwnershipInput <- sample(0:1, 1) #0 = yes, 1=no
  ExpensesInput <- sample(0:2, 1) #0 = above, 1=equal, 2=below
  Score <- 0
  
  x <- matrix(c(AgeInput, HomeInput, MentalHealthInput, PhysicalHealthInput, LivingWithInput, AllergiesInput, PriorOwnershipInput, ExpensesInput, Score), nrow = 1)
  
  # Add user's inputs to test set
  df.new = data.frame(x)
  Input.df <- rbind(Input.df, df.new)
}

# Assign each user an id
Input.df$id <- seq.int(nrow(Input.df))
names(Input.df) <- c("AgeInput", "HomeInput", "MentalHealthInput", "PhysicalHealthInput", "LivingWithInput", "AllergiesInput", "PriorOwnershipInput", "ExpensesInput", "Score", "id")
```

## set default weights
```{r}

  #cohens d
  Elderly <- 15.816
  Child <- 3.486
  DesireMentalHealth <- 17.35419784
  DesirePhysicalHealth <- 7.229100643
  HasAllergies <- -5.81
  House <- 9.71
  LivesAlone <- 5.34
  LivesWOthers <- 3.845
  HasPriorOwnership <- 2 
  LowerWillingnessToPay <- -27.25
  
  # odds-ratio
  # Elderly <- 25.568928
  # Child <- 4.3575
  # DesireMentalHealth <- 17.35419784
  # DesirePhysicalHealth <- 8.362460625
  # HasAllergies <- -6.45491
  # House <- 29.339743
  # LivesAlone <- 3.778483333
  # LivesWOthers <- 3.33245
  # HasPriorOwnership <- 2
  # LowerWillingnessToPay <- -44.7118

```

## Calculate "should you get a dog?" score for test set
```{r}

# For each user in test set, calculate their score using our "should you get a dog?" function
 for (i in 1:N) { 
   
    UserScore <- 0
  
  # Q: How old are you? 
      AgeInput <- Input.df$AgeInput[Input.df$id == i]
      # super elderly
      if (AgeInput >= 80) {
        UserScore <- UserScore + 0
      # elderly
      } else if (AgeInput >= 65) {
        UserScore <- UserScore + Elderly
      # adult  
      } else if (AgeInput > 18) {
        UserScore <- UserScore + 0
      # child
      } else {
        UserScore <- UserScore + Child
      }

  #Q: What is your home like?
      HomeInput <- Input.df$HomeInput[Input.df$id == i]
      # lives in a house
      if (HomeInput == 0) {
        UserScore <- UserScore +  House
      # lives in an apartment
      } else {
        UserScore <- UserScore +  0
      }
  
  #Q: Do you desire mental/emotional health benefits from owning a dog?
      MentalHealthInput <- Input.df$MentalHealthInput[Input.df$id == i]
      # desires mental/emotional health benefits
      if (MentalHealthInput == 0 ) {
          Score <- Score +  DesireMentalHealth
      # does not desire mental/emotional health benefits
      } else {
          Score <- Score +  0
      }

  #Q: Do you desire physical health benefits from owning a dog?
      PhysicalHealthInput <- Input.df$PhysicalHealthInput[Input.df$id == i]
      # desires physical health benefits
      if (PhysicalHealthInput == "Yes") {
        Score <- Score +  DesirePhysicalHealth
      # desires not desire physical health benefits
      } else {
        Score <- Score +  0
      }

  #Q: Do you live alone?
      LivingWithInput <- Input.df$LivingWithInput[Input.df$id == i]
      # lives alone
      if (LivingWithInput == 0) {
        UserScore <- UserScore +  LivesAlone 
      #lives with others
      } else {
        UserScore <- UserScore +  LivesWOthers
      }

  #Q: Are you or anyone in your household allergic to dogs?
      AllergiesInput <- Input.df$AllergiesInput[Input.df$id == i]
      # has allergies
      if (AllergiesInput == 0) {
        UserScore <- UserScore +  HasAllergies
      # does not have allergies
      } else {
        UserScore <- UserScore +  0
      }

  #Q: Have you owned a dog in the past?
      PriorOwnershipInput <- Input.df$PriorOwnershipInput[Input.df$id == i]
      # has prior dog ownership
      if (PriorOwnershipInput == 0) {
        UserScore <- UserScore +  HasPriorOwnership
      # does not have prior dog ownership
      } else {
        UserScore <- UserScore +  0
      }

  #Q: The average monthly cost of owning a dog is $171.24 (ranges from $55.47 - $395.69). Would you be able/willing to pay equal to that amount, below that amount or above that amount for your dog?
      ExpensesInput <- Input.df$ExpensesInput[Input.df$id == i]
      # willing/able to pay below monthly average
      if (ExpensesInput == 2) {
       UserScore <- UserScore +  LowerWillingnessToPay 
      # willing/able to pay equal or above monthly average
      } else {
          Score <- Score +  0
      }

  # Set user's test score as calculated score
  Input.df$Score[Input.df$id == i] <- UserScore
  
}
```
## Analyze Results
```{r}
# Plot distribution of scores for all users in test set
ScorePlot <- ggplot(Input.df, aes(id, Score)) + 
  geom_point()

ScorePlot <- ScorePlot + labs(x = "user")
ScorePlot <- ScorePlot  + geom_hline(yintercept = 0, color= "red") #theshold: score = 0
ScorePlot <- ScorePlot  + geom_hline(yintercept = mean(Input.df$Score), color="blue") #average score
ScorePlot

# Calculate the average score for test set
AverageScore <- mean(Input.df$Score)
print(AverageScore)

# Calculate how many users should and should not get a dog
ShouldGetADog <- count(Input.df, Input.df$Score > 0)
print(ShouldGetADog)
```
